CREATE TABLE Book (
    BookId BINARY(16) PRIMARY KEY,
    ISBN VARCHAR(20) NOT NULL UNIQUE,
    Title VARCHAR(500) NOT NULL,
    AuthorId BINARY(16) NOT NULL,
    CategoryId BINARY(16) NOT NULL,
    PublicationYear INT NULL,
    Publisher VARCHAR(255) NULL,
    Pages INT NULL,
    Language VARCHAR(50) DEFAULT 'Español',
    Description TEXT NULL,
    CoverImageUrl VARCHAR(500) NULL,
    BookStatusId BINARY(16) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_book_author FOREIGN KEY (AuthorId) REFERENCES Author(AuthorId) ON UPDATE CASCADE,
    CONSTRAINT fk_book_category FOREIGN KEY (CategoryId) REFERENCES Category(CategoryId) ON UPDATE CASCADE,
    CONSTRAINT fk_book_status FOREIGN KEY (BookStatusId) REFERENCES BookStatus(BookStatusId) ON UPDATE CASCADE,
    INDEX idx_book_isbn (ISBN),
    INDEX idx_book_title (Title),
    INDEX idx_book_author (AuthorId),
    INDEX idx_book_category (CategoryId),
    INDEX idx_book_status (BookStatusId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
