CREATE TABLE Configuration (
    ConfigurationId BINARY(16) PRIMARY KEY,
    ConfigKey VARCHAR(100) NOT NULL UNIQUE,
    ConfigValue VARCHAR(500) NOT NULL,
    ConfigType ENUM('INT', 'DECIMAL', 'STRING', 'BOOLEAN') NOT NULL DEFAULT 'STRING',
    DisplayName VARCHAR(100) NOT NULL,
    Description VARCHAR(255) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_config_key (ConfigKey)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
