CREATE TABLE Country (
    CountryId BINARY(16) PRIMARY KEY,
    CountryName VARCHAR(100) NOT NULL UNIQUE,
    CountryCode VARCHAR(3) NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_country_name (CountryName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
