CREATE TABLE User (
    UserId BINARY(16) PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password VARCHAR(500) NOT NULL,
    StatusId BINARY(16) NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_status FOREIGN KEY (StatusId) REFERENCES Status(StatusId) ON UPDATE CASCADE,
    INDEX idx_user_email (Email),
    INDEX idx_user_status (StatusId)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
